### ISSUE TITLE
Hidden all tools command

### ISSUE THREAD

**Issue by geoxluca** [potree/potree#605]
Hi everybody 
I would like to know if is it possible to hidden all tool command. So to leave the page only a simple viewer and not also an interrogation page.
How I can do it?
Thank you

**Comment by chuxiaonan** [comment]
Sure, what you should do is just set the render canvas a `z-index` high enough to keep tools you don't need out.

Check this out:
```css
#potree_annotation_container + cavas {
  z-index: 10000000;
}
```
